### ISSUE TITLE
Suggestion: add examples

### ISSUE THREAD

**Issue by NikitaIvanovV** [termbox/termbox2#19]
What do you think about adding an "Examples" heading in the README to include links to projects that use the library like in [tcell](https://github.com/gdamore/tcell)? Beside providing a real-world example, they can also indicate that the lib is actually usable. I've made [this program](https://github.com/NikitaIvanovV/ictree) with termbox2, it could be the first project to be mentioned.

**Comment by adsr** [comment]
Added
