### ISSUE TITLE
What does TB_INPUT_MOUSE do?

### ISSUE THREAD

**Issue by mitchellwrosen** [termbox/termbox2#20]
I read the docs in `termbox.h`, and a bit of the code, but it still isn't totally clear. Thanks :)

**Comment by git-bruh** [comment]
It enables mouse support so that you receive, `TB_KEY_MOUSE_*` events. The `x` and `y` fields in `struct tb_event` will be set to the coordinates where the mouse was scrolled/clicked.�

**Comment by adsr** [comment]
Added some docs. Thank you @mitchellwrosen and @git-bruh.
