### ISSUE TITLE
Warning generated when compiling

### ISSUE THREAD

**Issue by richardellwood** [termbox/termbox2#29]
When compiling, I get the following warning.
`
../include/termbox.h: In function ‘tb_present’:
../include/termbox.h:1466:25: warning: implicit declaration of function ‘wcwidth’
`

**Comment by adsr** [comment]
Are you invoking the compiler with `-D_XOPEN_SOURCE`? termbox tries to define that for you if it's not defined, but if you've included certain libc headers before termbox.h it may not work.

**Comment by richardellwood** [comment]
Yes, I was including <stdlib.h> before <termbox.h>.  I switched them and now the warning is gone.  Thank you.
