### ISSUE TITLE
Setting custom colors in 256 color mode

### ISSUE THREAD

**Issue by richardellwood** [termbox/termbox2#30]
Is there a way to customize the colors available in 256 color mode like ncurses' init_color(colornum, r, g, b)?  Thanks.

**Comment by adsr** [comment]
Hello, termbox doesn't support this. We'd have to implement parameterized strings. See the "Parameterized Strings" section in `man 5 terminfo`. Doable but would add a lot of complexity. 

You can however send your own escape codes with `tb_sendf`. It's the `initc` termcap if you want to check it out. Here are the parameterized escape does for some popular terminals:

```
adam@asx1c9:~/termbox2$ for t in xterm xterm-256color linux screen rxvt-256color rxvt-unicode Eterm; do infocmp -E $t | grep initc | grep ' = '; done
static char xterm_256color_s_initc[] = "\033]4;%p1%d;rgb:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\033\134";
static char linux_s_initc       [] = "\033]P%p1%x%p2%{255}%*%{1000}%/%02x%p3%{255}%*%{1000}%/%02x%p4%{255}%*%{1000}%/%02x";
static char rxvt_256color_s_initc[] = "\033]4;%p1%d;rgb:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\033\134";
static char rxvt_unicode_s_initc[] = "\033]4;%p1%d;rgb:%p2%{65535}%*%{1000}%/%4.4X/%p3%{65535}%*%{1000}%/%4.4X/%p4%{65535}%*%{1000}%/%4.4X\033\134";
```

**Comment by richardellwood** [comment]
Thanks.  I'll take a look at that.  I did make a little program that shows what all of the 256 colors are.

![colors](https://user-images.githubusercontent.com/69062738/173467255-e424e0f3-1080-4645-88a5-85dbbcc576a5.png)

They're actually a pretty nice selection as is.  Do you know if these are guaranteed to remain consistent?  I would be nice to pick certain colors and know that they'll look that way for other users.
