### ISSUE TITLE
Linter warnings

### ISSUE THREAD

**Issue by purpledan** [termbox/termbox2#42]
Hi there,

I use CLion for C-dev, its built-in linter gives hundreds of warnings, mostly of the "Macro blah is never used" kind. Ignoring those, since the nature of this library, there are other warnings such as "Clang-Tidy: Macro replacement list should be enclosed in parentheses", "Clang-Tidy: Potential uncovered code path; add a default label", and "Clang-Tidy: Narrowing conversion from 'uint32_t' (aka 'unsigned int') to signed type 'wchar_t' (aka 'int') is implementation-defined". It also complains about functions with no arguments, silenced by adding doing tb_width(void).

I am not asking that the project follow the "advice" of the linter, I would just like to know if this is something you care about or not, if not, why? I would like to know what the opinion is of those working on this project.

Apart from that, I like the suckless principle that went into this project, the small code base makes me very happy. I have recurring nightmares from working with ncurses. If at all possible, I'd like to contribute to this project.

**Comment by adsr** [comment]
Hi @purpledan, thanks for pointing that out. Yes, we care.

> "Clang-Tidy: Macro replacement list should be enclosed in parentheses"

This indeed can guard against subtle mistakes. If you fix this, `codegen.sh` will need to be updated to output parens around define values. The code in `tests/test_ffi.php` that extracts define values will need to be updated to handle these parens as well.

> "Clang-Tidy: Potential uncovered code path; add a default label"
> "Clang-Tidy: Narrowing conversion from 'uint32_t' (aka 'unsigned int') to signed type 'wchar_t' (aka 'int') is implementation-defined"

Sounds like a good idea to fix these.

> It also complains about functions with no arguments, silenced by adding doing tb_width(void).

Yes, technically that is the correct way to define a function that takes no args.

I'll add these to my backlog, but do feel free to submit PRs.

**Comment by adsr** [comment]
https://github.com/termbox/termbox2/pull/44
