### ISSUE TITLE
Change strerror to strerror_r in tb_strerror ?

### ISSUE THREAD

**Issue by git-bruh** [termbox/termbox2#43]
https://github.com/termbox/termbox2/blob/693bfca38cf0f5347db1050cdfbe76e97e0d4d16/termbox.h#L1833

This isn't thread safe, should it be switched to strerror_r or the thread unsafety be documented instead ?

**Comment by rofl0r** [comment]
`global` is a static struct, so termbox isn't threadsafe per se. also i can't see how it would make sense to have several threads manipulate the terminal singleton at the same time.

**Comment by git-bruh** [comment]
I was referring to the case you mentioned in the edit, where some other thread uses strerror() for an error unrelated to termbox

**Comment by adsr** [comment]
Seems like a good idea. Thanks.
