### ISSUE TITLE
noecho required

### ISSUE THREAD

**Issue by stolen-programmer** [termbox/termbox2#50]
Sorry, please forgive my poor English

I need the noecho function to hide the input

**Comment by adsr** [comment]
Hello, termbox disables echo via `cfmakeraw`. Feel free to re-open the ticket if you have an example where this is not working. In that case, please share source code, terminal emulator version, `$TERM` value. Thank you.

**Comment by stolen-programmer** [comment]
Oh, I'm sorry

I recently studied terminfo, but haven't figured out how to disable echo

I confused ncurses with termbox2
