### ISSUE TITLE
[meta] request for admin permission to the `termbox-haskell` repo

### ISSUE THREAD

**Issue by mitchellwrosen** [termbox/termbox2#52]
Hey! I was thinking of pulling the `termbox-haskell` repo out of this org and back under my own control. It seems to be the odd one out, as other language bindings are also in separate orgs.

But I'm not authorized to move the repo location (via `Settings`). Could I get permission?

Thanks :v:

**Comment by mitchellwrosen** [comment]
Ping!

**Comment by adsr** [comment]
Hi @mitchellwrosen I made you an admin. Let me know if that works for you.
