### ISSUE TITLE
Naming of files when termbox2 is installed as a library

### ISSUE THREAD

**Issue by frou** [termbox/termbox2#53]
Hi there - Is it too late to revisit the choice you went with in https://github.com/termbox/termbox2/pull/40 to not name installed library  and header files `termbox2`?

IMO the fact that the termbox2 project is in a completely separate repository makes it clear cut that it should be able to live side-by-side with the original termbox, without stepping on each other.

**Comment by adsr** [comment]
Added in a4f92ea
