### ISSUE TITLE
Add an example in Rust

### ISSUE THREAD

**Issue by rilysh** [termbox/termbox2#54]
Hello!

I've created an example (demo) w/ Rust. But I'm not sure whether I should create a PR or not, since the Rust demo isn't really portable as others that are available in the demo folder, e.g. Zig's example. Since Rust can't just directly use a C header file (as Zig or Go) calling functions from a shared library needs prototyping for them, so it's not kind of portable. However, if you feel this is okay to add [here](https://github.com/rilysh/termbox2-ww/blob/main/src/main.rs) is one.

**Comment by adsr** [comment]
Sure file a PR and if you'd like add a comment at the top of the file on how to run it.

**Comment by rilysh** [comment]
Alright, thanks for explaining the steps!
