### ISSUE TITLE
tb_init fails with -22 for an own test and for the example

### ISSUE THREAD

**Issue by winspool** [termbox/termbox2#57]
My own test app and the example in README.md fail in tb_init.

Returned result from 'tb_init()' is -22.

TERM is set to "xterm-color"
I use "xfce4-terminal"

termbox2 fails
termbox (by nsf) works
cursebox.c (fork of termbox) works

Adding "xterm-color" to the 'builtin_terms' table did not help.
(i tried it for every *caps entry ).

**Comment by adsr** [comment]
Thank you for the bug report. I'll tag you after pushing a fix this evening.

**Comment by adsr** [comment]
Can you try again with 80733af? Please reopen if not fixed. Thanks again for the report.

**Comment by winspool** [comment]
> Thank you for the bug report. I'll tag you after pushing a fix this evening. In the mean-time TERM=xterm-256color may work for you.

Overwriting "TERM" works.

**Comment by winspool** [comment]
> Can you try again with 80733af? Please reopen if not fixed. Thanks again for the report.

80633* and current head (f56f23)
fixed his issue. Thanks
