### ISSUE TITLE
Examples of `tb_set_cell_ex` / `tb_extend_cell`?

### ISSUE THREAD

**Issue by mitchellwrosen** [termbox/termbox2#59]
Hi, I'm having some difficulty understanding how to use `tb_set_cell_ex` and `tb_extend_cell` properly. Perhaps their usage could be highlighted in an example program?

Thanks!

**Comment by mitchellwrosen** [comment]
One comment: I think the comment on `nech` is wrong, which has contributed some confusion.

```c
    size_t nech;   /* length in bytes of ech, 0 means use ch instead of ech */
```

If I'm not mistaken, `nech` is the number of elements in the `'\0'`-terminated `ech` array, not including the null byte (and thus is never `1`, because `ch` would be used instead).

For example, if `ech` is the array `{ 1, 2, 3, 0 }`, then `nech` would be `3`.

Is that correct?

**Comment by adsr** [comment]
Yes, you have it right. I just pushed https://github.com/termbox/termbox2/commit/f5d6386ea580569cce8ea2bbfadd25de70291bfd which clarifies the docs and adds a test which demonstrates how to use `tb_set_cell_ex` and `tb_extend_cell`. The gist of it is:

```c
uint32_t egc[2] = {..., ...}; // or however many code points are in your cluster
tb_set_cell_ex(0, 0, egc, 2, 0, 0);

// or, the same effect using `tb_extend_cell`:
tb_set_cell(0, 0, egc[0], 0, 0);
tb_extend_cell(0, 0, egc[1]);

```

It also fixes a pretty glaring bug. Thanks for raising this.

**Comment by mitchellwrosen** [comment]
Nice, thank you!
