### ISSUE TITLE
mouse support

### ISSUE THREAD

**Issue by git-bruh** [termbox/termbox2#6]
Hi. Currently mouse support is marked as TODO: https://github.com/termbox/termbox2/blob/cb30c20dadf469021abd22004ea9365b7fad0c51/termbox.h#L2405

I'd like to implement it but not sure where to start. I guess we just need to move the escape sequences from the commented out code into the trie? Which makes me even more lost cuz all the `if` branches need to be handled too. 

Thanks

**Comment by adsr** [comment]
Mouse event parsing will need to stay in its own function unless we turn the trie code into something more complex like a LALR parser or something. I'd rather have one complex function than to make all of the trie code complex just for one special case.

Feel free if you want to take a shot at implementing it. It should recognize 1006, 1015, and vt200 mode mouse sequences, and it should return `TB_ERR_NEED_MORE` if it begins to match one of those modes but there is not enough data to fully parse. Also we should write some tests, at least for 1006 mode which xterm-like terminals seem to emit. If not I can probably find time to work on this soon within the next few weeks.
