### ISSUE TITLE
incorrect key mapping for `KEY_HOME` and `KEY_END`

### ISSUE THREAD

**Issue by sewbacca** [termbox/termbox2#68]
When I press `HOME` I get for `ch` `'H'` (72) and when I press CTRL+HOME I get `key` 65521 (KEY_HOME).
The same issue with `END`.

Side note: BACKSPACE gives `KEY_BACKSPACE2` and CTRL+BACKSPACE gives `KEY_BACKSPACE`, is this intended?

**Comment by adsr** [comment]
Hi, what terminal emulator are you using and can you share your `TERM` env var?

**Comment by sewbacca** [comment]
Sorry, this one is on me. I don't have correctly diagnosed my problem. The issue came from a modification I made and I forgot to rule out, that this is where the problem arose from.

As you can tell from my question in #67, I am trying to create something akin to readline, so I removed the `send_clear` command during `rwfd_init`, to get access to the non blocking io functionality in termbox (most of the keys work without a clear correctly, anyways), while don't destroying the scrollbackbuffer. As long as the screen is cleared once before polling the event, I receive the correct KEYS.

There are no Lua bindings for readline / linenoise / ncurses that compile on Windows (at least with my setup) and I already have created Lua bindings for termbox2, before realizing that I cannot write to the terminal without clearing the scrollback buffer. That's why I tried to make tb2 work with the normal scrollback buffer. I guess I'll get over my sunken cost fallacy and gonna try now to fix the compilation issues for the bindings of one of the other libraries.

Anyways, you may close this issue because it's basically unrelated, since clearing the buffer is an inbuilt assumption in tb2.
Sorry for taking up your time and thanks for creating this library. From what I've tried so far, it's amazingly simple, intuitive and works like a charm.

P.S. Because you asked, here's my terminal setup anyways:
I tested this using WSL (Ubuntu) and MinGW (with the PR)
using the emulators: WezTerm and Windows Terminal
`$TERM` gives for both emulators `xterm-256color`

**Comment by adsr** [comment]
Understood. Like I said in #67, maybe I'll write termline one day, and I'll add Windows support. I thought it was going to be harder to get termbox2 working in Windows, but it was easier than I thought thanks to xterm compat in recent Windows consoles.

**Comment by adsr** [comment]
@sewbacca I founds two forks of linenoise that claim to have Windows support. You may want to look at them. I don't know if they are still maintained though:
* [linenoise-ng](https://github.com/arangodb/linenoise-ng)
* [replxx](https://github.com/AmokHuginnsson/replxx)
