### ISSUE TITLE
Questions about limitations of termbox2

### ISSUE THREAD

**Issue by sewbacca** [termbox/termbox2#71]
Is it possible to query the mouse position? ncurses has `getxy()`. Polling `MOUSE_MOTION` events are only reported on drag.
Also is it possible to check which mouse key was released?

**Comment by sewbacca** [comment]
I am working on an interactive interpreter, which alows multiline inputs. For that reason CTRL+CR would be awesome to detect. It appears however, that tb2 can't distinguish in each mode, between the two inputs. Is that a fundamental limitation?

**Comment by adsr** [comment]
> Is it possible to query the mouse position? ncurses has getxy(). Polling MOUSE_MOTION events are only reported on drag.

There's DECELR but I'm not sure how widely supported it is. The terminal emulator I use (xfce4-terminal, which is vte-based) doesn't seem to support it[^1]. xterm supports it via a compile time option `--enable-dec-locator`, but Debian's package doesn't enable it. I think there may be a separate mouse tracking mode that does this in xterm, but similarly not sure how widely supported it is.

In a case like this, you could implement it in your application via `tb_sendf` (to send DECELR, or whatever mouse tracking mode escape code) and `tb_set_func` + `TB_FUNC_EXTRACT_PRE` (to extract events). This is a good use-case for those functions. I can try to write an example.

Isn't ncurses `getyx` for reporting the text cursor, not the mouse cursor?

> Also is it possible to check which mouse key was released?

In certain mouse modes, yeah I think so. As above, you can use `TB_FUNC_EXTRACT_PRE` if you want to try to parse these out yourself with the usual caveat that they likely won't on all terminals. I will go over the supported mouse modes and see if there is any incoming info we're not representing properly in the current API.

> I am working on an interactive interpreter, which alows multiline inputs. For that reason CTRL+CR would be awesome to detect. It appears however, that tb2 can't distinguish, in any mode, between the two inputs. Is that a fundamental limitation?

Assuming you mean C-enter, we could detect it if the terminal sent a different escape code for it. Linux console, xterm, and vte all seem to send `\r` for enter, C-enter, and S-enter. M-enter is distinct. Other terminal emulators may send distinct codes for C-enter -- I haven't tested. At the risk of sounding repetitive, you can again use `TB_FUNC_EXTRACT_PRE` to try to parse out any custom escape sequences not recognized by termbox2 internally.

Some terminals like the macOS default terminal app allow you to send an arbitrary escape code given a key input. You could potentially map C-enter to an F key.

[^1]: https://github.com/GNOME/vte/blob/4bb767c342c099cafffb760cd0e7a255a72e9578/src/vteseq.cc#L3047-L3066

**Comment by rofl0r** [comment]
getmouse() seems to be the proper way to get mouse coords in xterm.

**Comment by sewbacca** [comment]
> Isn't ncurses `getyx` for reporting the text cursor, not the mouse cursor?

Yes indeed; NeoVim however is able to somehow detect the mouse position, because the context menu reacts to mouse movement. They use ncurses, but maybe it's not ncurses itself that provides this functionality.

> Assuming you mean C-enter, we could detect it if the terminal sent a different escape code for it. Linux console, xterm, and vte all seem to send `\r` for enter, C-enter, and S-enter. M-enter is distinct. Other terminal emulators may send distinct codes for C-enter -- I haven't tested. At the risk of sounding repetitive, you can again use `TB_FUNC_EXTRACT_PRE` to try to parse out any custom escape sequences not recognized by termbox2 internally.

I knew about `tb_set_func`, but didn't exactly understand how they work or their purpose. Writing to the terminal works via invoking `tb_send`, but there is no `tb_read` functionality. Should I just read from `stdin`? Can I even assume that stdin is always used (because of `init_fd`)?

**Comment by adsr** [comment]
Below is an example of working mouse motion capture for xterm. Turns out there was no need for `tb_set_func`. Just had to enable 1003 mode. (1006 is already enabled in mouse mode.) The existing `extract_esc_mouse` implementation already parses out motion events conveniently. I'm curious if it works for you in the Windows terminal.

```c
#define TB_IMPL
#define TB_LIB_OPTS
#include "termbox2.h"

#include <stdlib.h>
#include <time.h>

int main(int argc, char **argv) {
    srand(time(NULL));

    (void)argc;
    (void)argv;

    tb_init();
    tb_set_input_mode(TB_INPUT_MOUSE);
    tb_set_output_mode(TB_OUTPUT_TRUECOLOR);

    // 1003 "Any-event tracking" mode
    // 1006 SGR extended coordinates (already enabled with TB_INPUT_MOUSE)
    tb_sendf("\x1b[?%d;%dh", 1003, 1006);
    tb_present();

    struct tb_event e;
    int rv;
    while (1) {
        rv = tb_poll_event(&e);
        if (!(rv == TB_OK || (rv == TB_ERR_POLL && tb_last_errno() == EINTR))) {
            break;
        } else if (e.type == TB_EVENT_KEY && e.ch == 'q') {
            break;
        } else if (e.type == TB_EVENT_MOUSE) {
            tb_print(e.x, e.y, 0, rand() % 0xffffff, " ");
            tb_set_cursor(e.x, e.y);
            tb_printf(0, 0, 0, 0, "key=%d mod=%d", e.key, e.mod);
        }
        tb_present();
    }

    tb_sendf("\x1b[?%d;%dl", 1003, 1006);
    tb_shutdown();

    return 0;
}
```

There's enough info there to distinguish between clicks and motion. If you want to know what button was released I'd recommend tracking the last button pressed in your application. Release button may be part of other mouse protocols but not this xterm one.

> but there is no tb_read functionality. Should I just read from stdin? Can I even assume that stdin is always used (because of init_fd)?

This was my mistake in the `tb_set_func` API. Next ABI version I'm going to either change the API to use void pointers to make it more generic for future callbacks, or rename it to `tb_set_extract_func` and change the callback type to include the input buffer. I regret adding it without thinking it over more clearly. The callback would ideally look like:

```c
typedef int (*tb_extract_fn)(const char *buf, size_t nbuf, struct tb_event *e, size_t *nconsumed);
```
The idea is you'd check if your escape sequence is in `buf` and if so populate the event, pass back how many bytes you consumed, and return `TB_OK`. If it doesn't look like your sequence, return `TB_ERR`. If it looks like a prefix of your sequence, return `TB_ERR_NEED_MORE`.

**Comment by sewbacca** [comment]
> Below is an example of working mouse motion capture for xterm. Turns out there was no need for `tb_set_func`. Just had to enable 1003 mode. (1006 is already enabled in mouse mode.) The existing `extract_esc_mouse` implementation already parses out motion events conveniently. I'm curious if it works for you in the Windows terminal.

Yes it works perfectly on any Windows terminal I tried. This is amazing, thanks!

> This was my mistake in the `tb_set_func` API. Next ABI version I'm going to either change the API to use void pointers to make it more generic for future callbacks, or rename it to `tb_set_extract_func` and change the callback type to include the input buffer. I regret adding it without thinking it over more clearly.

So I just extract bytes from stdin then, and set the used size to the passed in pointer in the current API?

**Comment by adsr** [comment]
Sorry I missed your last comment. I'm glad it worked for you.

> So I just extract bytes from stdin then, and set the used size to the passed in pointer in the current API?

I'm not sure that will work because at that point termbox has already read from the tty. The API is really broken. Definitely my bad. If you really needed to, you could maybe pull it off by shadowing the tty fd before you initialize termbox.

**Comment by tokyovigilante** [comment]
> This was my mistake in the `tb_set_func` API. Next ABI version I'm going to either change the API to use void pointers to make it more generic for future callbacks, or rename it to `tb_set_extract_func` and change the callback type to include the input buffer. I regret adding it without thinking it over more clearly. The callback would ideally look like:
> 
> typedef int (*tb_extract_fn)(const char *buf, size_t nbuf, struct tb_event *e, size_t *nconsumed);
> 
> The idea is you'd check if your escape sequence is in `buf` and if so populate the event, pass back how many bytes you consumed, and return `TB_OK`. If it doesn't look like your sequence, return `TB_ERR`. If it looks like a prefix of your sequence, return `TB_ERR_NEED_MORE`.

Hi, I'm hoping to use `tb_set_func` to non-invasively support FocusIn and FocusOut events (`CSI I` and `CSI 0`), and just wanted to confirm there would be a similar API going forward. Alternatively is this something people would want in the core API?

**Comment by tokyovigilante** [comment]
> Hi, yes, I think it's useful. There's a never-ending list of escape sequences and trying to support them all gets messy. IMO the user-supplied callback is a good solution for this. Look out for a version 3 PR soon, which should include this.

Awesome, thanks! I've settled on this in the meantime, which wraps the old `tb_set_func` internally and makes the new API available externally (to Nim code in my case) but happy to put together a PR replacing/alongside `tb_set_func()`:

```c
#include <stddef.h>  /* for size_t */

/* Forward declaration */
struct tb_event;

/* New callback type that receives the buffer directly */
typedef int (*tb_extract_fn)(const char *buf, size_t nbuf, struct tb_event *e, size_t *nconsumed);

/* Function to set the new extraction callback */
int tb_set_extract_func(tb_extract_fn fn);

#define TB_IMPL
#include "termbox2.h"

/* Global variable to store the custom extraction function */
static tb_extract_fn global_extract_fn = NULL;

/* Wrapper for the old tb_set_func API that uses the new callback */
static int extract_wrapper(struct tb_event *event, size_t *consumed) {
    if (!global_extract_fn) {
        return TB_ERR;
    }
    
    /* Access the input buffer from termbox2's global state */
    extern struct tb_global_t global;
    struct bytebuf_t *in = &global.in;
    
    /* Call the new-style callback with the buffer */
    return global_extract_fn(in->buf, in->len, event, consumed);
}

/* Set the extraction function */
int tb_set_extract_func(tb_extract_fn fn) {
    global_extract_fn = fn;
    
    /* Register with termbox2 using the old API */
    if (fn) {
        return tb_set_func(TB_FUNC_EXTRACT_PRE, extract_wrapper);
    } else {
        return tb_set_func(TB_FUNC_EXTRACT_PRE, NULL);
    }
}
```
