### ISSUE TITLE
`tb_clear` not clearing the screen properly when using emoji

### ISSUE THREAD

**Issue by Strahinja** [termbox/termbox2#73]
Using the [current _termbox2.h_](https://github.com/termbox/termbox2/blob/ff767c1e8452bc19e24760df9a82b4c0c50f096f/termbox2.h) in OpenBSD -release 7.5 and:
* xterm (`XTerm/OpenBSD(378)`) with `TERM=xterm-256color`,
* rxvt-unicode (`rxvt-unicode-9.31p2-everything`) with `TERM=rxvt-256color` or
* st 0.9.2 + [some patches](https://git.sr.ht/~strahinja/st/tree/472abd28c016a83f6da4ed4da28763ca8750c663/item/applied) with `TERM=st-256color`,

it seems that `tb_clear` isn't clearing the screen properly when there are emoji characters in the output.

Pressing `Space` in the following example program toggles between outputting the string with the character `0x1F527` and without it (simulating, eg. pressing backspace to erase the character in an editor).
```c
#define TB_IMPL
#include "termbox2.h"

#define LEN(x) (sizeof(x)/sizeof(x[0]))
int
main(void)
{
	struct tb_event ev;
	uint32_t str1[] = { 0x61, 0x73, 0x64, 0x66, 0x1F527, 0x20,
			0x444, 0x43E, 0x43D, 0x442 };
	uint32_t str2[] = { 0x61, 0x73, 0x64, 0x66, 0x20,
			0x444, 0x43E, 0x43D, 0x442 };
	uint32_t* ps;
	int result, toggle, w, x, len;
	toggle = 0;
	tb_init();
	while (1)
	{
		if (toggle)
		{
			ps = str2;
			len = LEN(str2);
		}
		else
		{
			ps = str1;
			len = LEN(str1);
		}
		tb_set_clear_attrs(TB_WHITE, TB_BLACK);
		tb_clear();
		x = 0;
		for (int i = 0; i < len; i++)
		{
			w = wcwidth((wchar_t)ps[i]);
			if (w < 0)
				w = 1;
			if (w != 0)
				tb_set_cell(x, 2, ps[i],
					TB_WHITE | TB_BOLD, TB_RED | TB_DIM);
			x += w;
		}
		tb_present();
		result = tb_poll_event(&ev);
		if (result == TB_OK && ev.type == TB_EVENT_KEY)
		{
			if(ev.ch == 'q')
				break;
			else if(ev.ch == ' ')
				toggle = !toggle;
		}
	}
	tb_shutdown();
}
```
Even though `tb_clear` is used, there are some leftover artefacts:
![2024-07-11-224143-dwm](https://github.com/user-attachments/assets/b1f19ddd-9970-4103-9ebd-bddbb59fa041)

Using the same terminals and editing the same text with eg. vim, pressing `Backspace` directly after the emoji, produces no artefacts, leading to the conclusion that this is a bug in termbox.

**Comment by adsr** [comment]
Hi, I think that'll happen if you send UTF-8 in C locale (which causes `wcwidth(3)` to return 1 for a multi-width characters like `🔧`). Assuming you have the appropriate env vars set, you should call `setlocale(LC_ALL, "")` at the beginning of your program to get out of the default C locale. Can you try that?

At the very least we can mention this in documentation.

I've thought about calling setlocale in `tb_init` but that has a lot of implications, so I figure it was best left up to the library user.

Another option is to include something like [wcwidth9](https://github.com/joshuarubin/wcwidth9) in termbox2. It would add some bloat (mostly big static arrays) but also kind of fits nicely with the existing `tb_utf8_*` functions.

**Comment by Strahinja** [comment]
I can confirm that adding
```
#include <locale.h>

/* main ... */

        setlocale(LC_ALL, "");
```
solved the issue.

I think that, given the nature of termbox being a single-header terminal library, this, combined with a mention in _README.md_ (maybe included in the example), might be a better approach than including more code in _termbox2.h_, possibly behind more `#ifdef`s.

I'm closing this issue, thank you!
